version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.16
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6-node'
      # - image: circleci/python:2.7-node
    environment:
      AWS_REGION: us-east-1
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          from: dist
          to: 's3://kiriaze-demo-ci-cd/'
          overwrite: true
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
